apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-audit-store
spec:
  type: state.mongodb
  metadata:
  - name: host
    value: state-mongodb-0.state-mongodb-headless.data.svc.cluster.local:27017
  - name: username
    value: dapr
  - name: password
    secretKeyRef:
      name: mongo-secret
      key: mongodb-password
  - name: databaseName
    value: dapr
  - name: collectionName
    value: audit
scopes:
- order-auditor