apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-queue
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: redis-master.data.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: password
scopes:
- order-auditor
- workflows-host
- order-viewer