apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: app2-config
  namespace: hardened
spec:
  tracing:
    samplingRate: "1"
  accessControl:
    defaultAction: deny
    trustDomain: "public"
    policies:
    - appId: app1
      defaultAction: deny 
      trustDomain: "public"
      namespace: "hardened"
      operations:
      - name: /ping
        httpVerb: ["POST"] 
        action: allow