apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-depth-scaler
spec:
  scaleTargetRef:
    name: autoscaling-subscriber
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      topic: messages
      bootstrapServers: kafka-cp-kafka-headless.kafka.svc.cluster.local:9092
      consumerGroup: autoscaling-subscriber
      lagThreshold: "5"