apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: autoscaling-kafka-queue
spec:
  type: pubsub.kafka
  metadata:
    - name: brokers
      value: "localhost:9092"
    - name: authRequired
      value: "false"
    - name: consumerID
      value: "autoscaling"