apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets
spec:
  type: bindings.twitter
  metadata:
    # secrets intentionally left in prep for Mark F's demo
    # TODO: remove before opening up the repo 
  - name: accessSecret
    secretKeyRef:
      name: demo-twitter-secrets
      key: access-secret
  - name: accessToken
    secretKeyRef:
      name: demo-twitter-secrets
      key: access-token
  - name: consumerKey
    secretKeyRef:
      name: demo-twitter-secrets
      key: consumer-key
  - name: consumerSecret
    secretKeyRef:
      name: demo-twitter-secrets
      key: consumer-secret
  - name: query
    value: "microsoft" # need more tweets during dev ;) 
    # value: "serverless"