apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-outoscaling-producer
  labels:
    app: queue-outoscaling-producer
    demo: autoscaling-producer
spec:
  selector:
    matchLabels:
      app: queue-outoscaling-producer
  template:
    metadata:
      labels:
        app: queue-outoscaling-producer
        demo: autoscaling-producer
    spec:
      containers:
      - name: producer
        image: mchmarny/queue-outoscaling-producer:v0.10.1
        env:
        - name: KAFKA_BROKER
          value: kafka-cp-kafka-headless.data.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: messages
        - name: NUMBER_OF_THREADS
          value: "4"
        - name: THREAD_PUB_FREQ
          value: "10ms"