apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweet
spec:
  type: bindings.twitter
  metadata:
  - name: consumerKey
    value: "qKorHpXCkva3xvlZvqCNSlliq" # twitter api consumer key, required
  - name: consumerSecret
    value: "bxoG2QkLtxfzmTtEmMP6Uv7S083OWQ6IlkBIftOq3ZkUUlGees" # twitter api consumer secret, required
  - name: accessToken
    value: "6697972-vyTrvPPzlvM6vZvlZf4Vblj7hUmvSVmccZFrmpu8U5" # twitter api access token, required
  - name: accessSecret
    value: "TyDiptdxg3irpNGTiubrghkdCLvaUcgO2oDsGL4iDDMJQ" # twitter api access secret, required
  - name: query
    value: "microsoft" # your search query, required 
---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: publishTweet
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: producerStateStore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""

