apiVersion: v1
kind: Service
metadata:
  name: dapr-cron-binding-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dapr-cron-binding-demo
  type: LoadBalancer
