apiVersion: v1
kind: Pod
metadata:
  name: autoscaling-producer
spec:
  containers:
  - name: producer
    image: mchmarny/autoscaling-producer:v0.10.5
    env:
    - name: KAFKA_BROKER
      value: "kafka.data.svc.cluster.local:9092"
    - name: KAFKA_TOPIC
      value: "prime-requests"
    - name: NUMBER_OF_THREADS
      value: "1"