apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-outoscaling-subscriber
  labels:
    app: queue-outoscaling-subscriber
    demo: autoscaling-demo
spec:
  selector:
    matchLabels:
      app: queue-outoscaling-subscriber
  template:
    metadata:
      labels:
        app: queue-outoscaling-subscriber
        demo: autoscaling-demo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "queue-outoscaling-subscriber"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "60022"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: service
        image: mchmarny/queue-outoscaling-subscriber:v0.10.1
        ports:
        - containerPort: 60022
        env:
        - name: ADDRESS
          value: ":60022"
        - name: BINDING_NAME
          value: "autoscaling-kafka-queue"
        - name: PROCESS_DURATION
          value: "300ms"