apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: prime-calculator-scaler
  labels:
    deploymentName: queue-outoscaling-subscriber
spec:
  scaleTargetRef:
    deploymentName: queue-outoscaling-subscriber
  pollingInterval: 3
  cooldownPeriod:  20
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.data.svc.cluster.local:9092
      consumerGroup: autoscaling
      topic: messages
      lagThreshold: "3"