apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: prime-calculator-scaler
  labels:
    deploymentName: queue-prime-calculator
spec:
  scaleTargetRef:
    deploymentName: queue-prime-calculator
  pollingInterval: 5
  cooldownPeriod:  60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.data.svc.cluster.local:9092
      consumerGroup: autoscaling
      topic: primes
      lagThreshold: "10"