apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: hardened
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: redis-master.redis.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: password
  - name: publishingScopes
    value: "app1=messages"
  - name: subscriptionScopes
    value: "app2=messages"
scopes:
- app1
- app2