apiVersion: v1
kind: Service
metadata:
  name: grpc-event-subscriber
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: grpc-event-subscriber
  type: LoadBalancer
