apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-binding
  labels:
    app: twitter-binding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-binding
  template:
    metadata:
      labels:
        app: twitter-binding
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "twitter-binding"
        dapr.io/port: "8080"
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: service
        image: mchmarny/twitter-binding:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DAPR_HTTP_PORT
          value: "3500"