apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: source-event-binding
spec:
  type: bindings.azure.eventhubs
  metadata:
  - name: connectionString      
    secretKeyRef:
      name: eventhubConn
  - name: consumerGroup
    value: "demo"
  - name: storageAccountName
    value: "fanoutdemo"   
  - name: storageAccountKey
    secretKeyRef:
      name: storageAccountKey
  - name: storageContainerName
    value: "fanoutdemo"
auth:
    secretStore: fanout-secrets