apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fanout-http-source-event-binding
spec:
  type: bindings.azure.eventhubs
  metadata:
  - name: connectionString      
    secretKeyRef:
      name: eventhubConnStr
  - name: consumerGroup
    value: "fanouthttp"
  - name: storageAccountName
    value: "fanoutdemo"   
  - name: storageAccountKey
    secretKeyRef:
      name: storageAccountKey
  - name: storageContainerName
    value: "fanoutdemo"
  - name: partitionID
    value: "0"
auth:
    secretStore: fanout-secrets