name: git-ops release on tag

on:
  push:
    tags:
      - 'gitops-v*' # gitops-v0.1.1

jobs:

  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${GITHUB_REF:10}
      BUILD_TIME: "2020-11-14T06:28:32"
    steps:

    - name: Setup
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout
      id: setup
      uses: actions/checkout@v2

    - name: Tidy
      run: |
        cd git-ops/app
        go mod tidy 
        go mod vendor

    - name: Test
      run: |
        cd git-ops/app
        go test -v -count=1 -race ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Push
      uses: docker/build-push-action@v2
      with:
        context: ./git-ops/app
        file: ./git-ops/app/Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        push: true
        tags: "ghcr.io/${{ github.actor }}/git-ops-app:${{ env.RELEASE_VERSION }}"
        build-args: |
            APP_VERSION=${{ env.RELEASE_VERSION }}
            BUILD_TIME=${{ env.BUILD_TIME }}
